Only team matches get displayed
Eixix/sili-telegram-bot pull request #30
Opened 2022-07-04 15:01 UTC by Eixix

2022-07-04 16:21 UTC, Cormochamelion approved these changes
LGTM 👍

2022-07-04 18:03 UTC, 1Joghurt commented
Abfrage muss weiter hoch - jetzt werden erst die Zeilen der Nachricht aufbereitet, um sie dann ggf. zu verwerfen. Anzahl ist bereits früher bekannt.

2022-07-05 18:54 UTC, 1Joghurt requested changes
Wie bereits beschrieben

2022-07-05 19:18 UTC, 1Joghurt approved these changes

2022-07-05 19:19 UTC, merged